version: '3.8'

services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: librarydb
      MYSQL_USER: libraryuser
      MYSQL_PASSWORD: librarypass
    ports:
      - "3306:3306"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql

  payara:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "4848:4848"
    volumes:
      - ./target/book-library-backend.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/book-library-backend.war
      - ./drivers/mysql-connector-j-8.4.0.jar:/opt/payara/appserver/glassfish/domains/domain1/lib/ext/mysql-connector-j-8.4.0.jar
      - ./setup-datasource.asadmin:/opt/payara/setup-datasource.asadmin
      - ./password.txt:/opt/payara/password.txt
    command: >
      bash -c "
        /opt/payara/appserver/bin/asadmin start-domain &&
        sleep 10 &&
        expect -c '
          spawn /opt/payara/appserver/bin/asadmin change-admin-password --user admin --domain_name domain1
          expect \"Enter the admin password:\"
          send \"\r\"
          expect \"Enter the new admin password:\"
          send \"admin123\r\"
          expect \"Enter the new admin password again:\"
          send \"admin123\r\"
          expect eof
        ' &&
        sleep 5 &&
        /opt/payara/appserver/bin/asadmin --user admin --passwordfile /opt/payara/password.txt --port 4848 --host localhost < /opt/payara/setup-datasource.asadmin &&
        tail -f /opt/payara/appserver/glassfish/domains/domain1/logs/server.log
      "
    restart: unless-stopped
